version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  say-hello:
    executor: node/default
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: | 
            echo Hello, World!
            echo Here is Damien
            
        

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
