version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  say-hello:
    executor: node/default
    steps:
      - checkout
      - run:
          name: "A test"
          command: | 
            echo testing
            npm i
            npm i enzyme2222
            npm test
            
        

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
